### ISSUE TITLE
Surplus/Redundant/Unnecessary Inference

### ISSUE THREAD

**Issue by Justin62628** [HolyWu/vs-gmfss_union#2]
https://github.com/HolyWu/vs-gmfss_union/blob/c8099206bdb6027f5a9a5bcbe6a92e9df94a17e4/vsgmfss_union/gmfss.py#L52
The `Reuse` part is designed to calculate optical flow and features which can be reused when fusing/inferencing frames at different/arbitrary timestep.
Thus, the `GMFSS` class should be split into two part for sake of TRT to avoid redundant inference (if necessary/convenient), whose pseudocode probably looks like:

```python
class Reuse(nn.Module):
    ...
    def forward(img0, img1):
        ...
        return reuse_things

class GMFSS(nn.Module):
    ...
    def forward(img0, img1, reuse_things, timestep):
        ...
        return self.fusionnet(img0, img1, reuse_things, merged, timestep)

inst_reuse = Reuse(...)
inst_gmfss = GMFSS(...)
    
def inference(n: int, f: list[vs.VideoFrame]) -> vs.VideoFrame:
    ...
    reuse_things = inst_reuse(img0, img1)  # this takes up 30% of the time according to our inspection
    timesteps = [timestep...]
    for t in timesteps:  # I don't know how to implement the sequential logic in VS(probably using packet or async? no idea, so filled with a for loop here
    	output = inst_gmfss(img0, img1, reuse_things, timestep)  # the left 70% calculation ends up here
    ...

```

**Comment by styler00dollar** [comment]
`Reuse` can not be efficiently used in vapoursynth, since multi image output is slower than just using one image output. At least in my testing. Would be nice if someone can manage to get reuse to be efficient in vapoursyth.

**Comment by Justin62628** [comment]
the time consumed by the two parts seems to have been measured wrongly, re-measuring. the `gmfss` part is much slower compared to `reuse`(gmf part actually)
