### ISSUE TITLE
portable version CUDA_PATH 

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-gmfss_union#3]
With other torch filters, I can usually place all cuda&co filter into a single folder and I can add that folder with:
```
# Adding torch dependencies to PATH
path = site.getsitepackages()[0]+'/torch_dependencies/'
ctypes.windll.kernel32.SetDllDirectoryW(path)
path = path.replace('\\', '/')
os.environ["PATH"] = path + os.pathsep + os.environ["PATH"]
```
First I thought, it would be enough, if I additionally set `os.environ["CUDA_PATH"] = path`.
But then I get:
[code]Python exception: [WinError 2] Das System kann die angegebene Datei nicht finden: 'I:/Hybrid/64bit/Vapoursynth/torch_dependencies/bin'[/code]
If I copy all my dlls into a bin-subfolder of torch_dependencies it works.

Would be nice if vs-gmfss_union would also directly use in the CUDA_PATH and not require a bin-subfolder, or if one could specify the folder where the filter should look manually.

**Comment by HolyWu** [comment]
I cannot do anything about that. It's hard-coded in https://github.com/cupy/cupy/blob/beac32813e400b6ec92d29aaceff0a6889275455/cupy/_environment.py#L211 because that's the official directory structure you will get after installing CUDA Toolkit.

**Comment by Selur** [comment]
Thanks for looking into it. :)
